In [2]:
import json
import pandas as pd
import numpy as np
import pickle

In [3]:
# import filtered business_id as dataframe from pickle
with open('data/yelp-dataset/df_business.pickle', 'rb') as fp:
    df_business_id = pickle.load(fp)
print(df_business_id.name)
df_business_id.shape

business_id

(38117,)

In [7]:
df_business_id

2         O8S5hYJ1SMc8fA4QBtVujA
11        tZnSodhPwNr4bzrwJ1CSbw
16        r89Re4FNgVWHgBfjCVZyVw
19        vJIuDBdu01vCA8y1fwR1OQ
23        5J3b7j3Fzo9ISjChmoUoUA
32        kgffcoxT6BQp-gJ-UQ7Czw
33        0jtRI7hVMpQHpUVtUy4ITw
37        qHF2s8U2yzPLgIOGH_IMBw
44        0i6GlR5YTCMlwthjqw6ZTQ
45        oSS0p8TeF9BTTD7QWtO6gg
50        DR30lzIHVTF6xhyMI-3IlQ
52        VVtPNiqwtR_Os7J51mANGQ
80        YIez_A3WOt9J2SXN7OMa2Q
82        xuUzASHWjRJRFv6Ck5pO7g
88        mr3rQcYBKWu2L6o7qtQ9Wg
95        Q_cfbLdAxkLiEZW5TO5T6A
96        Ea5a2Ov4s_D3Vx4j7jkEEg
97        cuXCQM-9VwpZlSneEY1b3w
110       pnYDtPaVw_xRBHm9y0y4gg
111       hsWx7ya8jLMhi8ZWX23Thg
118       -26MGfikhJiTfCI-GqmzhQ
123       lBzZKw6FYxbin9de9GAhTQ
126       i2Fd0dl39BZ8nVxBnSPsKg
129       2j5hnwYzS-YLJn6IFqloCw
131       OLg1IeS-QxZgNprQ4Hg9gg
134       hU9R0xQiZb2_b8tZituFYA
137       735UkyT4px_oeW3iyotGmA
141       zhxnD7J5_sCrKSw5cwI9dQ
143       2kWrSFkIes_d2BMg4YrRtA
146       _T8qy9XAKAFLJdmoLg1Q-g
                   ...
188499    CsLKFf9o7d9YZO2hsu6hzA
188500    bWZ6xFCL9FeAUPFmbAgAAw
188502    B8zlK5jEGAUJtIfhLA71jw
188505    QmJCAjen_OK_wU53XmMosg
188516    _eysP-l3yXpCqMHOQEptdQ
188517    dxBeA7XHTlBQKu9ypEJxwg
188529    3zJdvcJldp8OTYfaQhy6Iw
188530    p2qoi-QKUs_p6QkDEKVNOg
188536    Ykn6eHLY8vPHuUH7UQrvxw
188538    W5d8iNog90R-qw43m5dGwg
188539    rbXaYPyC6qSYzeggPcbHYQ
188540    96O69oTa04Dnu1m1pyzY7w
188541    _z0G1mVB_vQmT2aNqfZXKA
188545    eW1EJrcMDIQMHpW4fJxg2w
188547    qjyOjCHG9lOkZnAa8jIQ1g
188548    wK6bv6_TKdbAswbMNfO_2w
188549    Sgkwj5jlFQjpZnb4ASLuxw
188558    H1I6hoLA02U5huKlt9wVRA
188566    m75vszskLJ1a14Ybco4IaA
188568    v62o0cbntlpDXYaJtO9Lmw
188569    CorrByydi35r-6SvmhYFHA
188570    K9ukZjvXhDjQZnrrOPqKSw
188572    GdGXb80QKTMRP7AdPHDnuw
188573    JUygwe5d_MXCCOdk0WB30g
188580    -3bL-QmK7-qBYLmQuSekBw
188582    i3AziW_jq009bm26PLXdLA
188583    FxEoO2etCPrPLFOnGwV-Ww
188584    jYU4Nd71giCWpLuj5JIxgg
188585    Y_7sZoSLTJ-2mNZS8JS5Pg
188592    NkOvIueadjFUxeCyq_uQEw
Name: business_id, Length: 38117, dtype: object

In [4]:
# readin user.json
with open('data/yelp-dataset/yelp_academic_dataset_user.json') as fp:
    json_user = fp.readlines()
json_user[:2]

['{"user_id":"lzlZwIpuSWXEnNS91wxjHw","name":"Susan","review_count":1,"yelping_since":"2015-09-28","friends":"None","useful":0,"funny":0,"cool":0,"fans":0,"elite":"None","average_stars":2.0,"compliment_hot":0,"compliment_more":0,"compliment_profile":0,"compliment_cute":0,"compliment_list":0,"compliment_note":0,"compliment_plain":0,"compliment_cool":0,"compliment_funny":0,"compliment_writer":0,"compliment_photos":0}\n',
 '{"user_id":"XvLBr-9smbI0m_a7dXtB7w","name":"Daipayan","review_count":2,"yelping_since":"2015-09-05","friends":"None","useful":0,"funny":0,"cool":0,"fans":0,"elite":"None","average_stars":5.0,"compliment_hot":0,"compliment_more":0,"compliment_profile":0,"compliment_cute":0,"compliment_list":0,"compliment_note":0,"compliment_plain":0,"compliment_cool":0,"compliment_funny":0,"compliment_writer":0,"compliment_photos":0}\n']

In [6]:
# Create dataframe and filter by cities
list_ = []
for i_line in json_user:
    list_.append(json.loads(i_line))

df_user = pd.DataFrame(list_)
# print('before fileter', df_user.shape)
# print('no NaN, as show in isna():', df_user.isna().sum())
# df_user = df_user[df_user['business_id'].isin(df_business_id)]
# print('after filter', df_user.shape)
df_user.head()

,average_stars,compliment_cool,compliment_cute,compliment_funny,compliment_hot,compliment_list,compliment_more,compliment_note,compliment_photos,compliment_plain,...,cool,elite,fans,friends,funny,name,review_count,useful,user_id,yelping_since
0,2.00,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Susan,1,0,lzlZwIpuSWXEnNS91wxjHw,2015-09-28
1,5.00,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Daipayan,2,0,XvLBr-9smbI0m_a7dXtB7w,2015-09-05
2,4.00,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Andy,1,0,QPT4Ud4H5sJVr68yXhoWFw,2016-07-21
3,4.05,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Jonathan,19,0,i5YitlHZpf0B3R0s_8NVuw,2014-08-04
4,3.00,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Shashank,3,0,s4FoIXE_LSGviTHBe8dmcg,2017-06-18

In [7]:
df_user = pd.DataFrame(list_)
df_user.head()

,average_stars,compliment_cool,compliment_cute,compliment_funny,compliment_hot,compliment_list,compliment_more,compliment_note,compliment_photos,compliment_plain,...,cool,elite,fans,friends,funny,name,review_count,useful,user_id,yelping_since
0,2.00,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Susan,1,0,lzlZwIpuSWXEnNS91wxjHw,2015-09-28
1,5.00,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Daipayan,2,0,XvLBr-9smbI0m_a7dXtB7w,2015-09-05
2,4.00,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Andy,1,0,QPT4Ud4H5sJVr68yXhoWFw,2016-07-21
3,4.05,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Jonathan,19,0,i5YitlHZpf0B3R0s_8NVuw,2014-08-04
4,3.00,0,0,0,0,0,0,0,0,0,...,0,None,0,None,0,Shashank,3,0,s4FoIXE_LSGviTHBe8dmcg,2017-06-18

In [8]:
print(df_user.isna().sum())
print(df_user.size)
df_user.info

average_stars         0
compliment_cool       0
compliment_cute       0
compliment_funny      0
compliment_hot        0
compliment_list       0
compliment_more       0
compliment_note       0
compliment_photos     0
compliment_plain      0
compliment_profile    0
compliment_writer     0
cool                  0
elite                 0
fans                  0
friends               0
funny                 0
name                  0
review_count          0
useful                0
user_id               0
yelping_since         0
dtype: int64
33399718

<bound method DataFrame.info of          average_stars  compliment_cool  compliment_cute  compliment_funny  \
0                 2.00                0                0                 0
1                 5.00                0                0                 0
2                 4.00                0                0                 0
3                 4.05                0                0                 0
4                 3.00                0                0                 0
5                 5.00                0                0                 0
6                 5.00                0                0                 0
7                 5.00                0                0                 0
8                 2.77                0                0                 0
9                 4.00                0                0                 0
10                5.00                0                0                 0
11                4.20                0                0                 0
12                3.86                0                0                 0
13                2.00                0                0                 0
14                2.00                0                0                 0
15                3.00                0                0                 0
16                1.00                0                0                 0
17                4.00                0                0                 0
18                3.75                0                0                 0
19                3.00                0                0                 0
20                4.00                0                0                 0
21                1.00                0                0                 0
22                3.00                0                0                 0
23                4.50                0                0                 0
24                4.20                0                0                 0
25                4.00                0                0                 0
26                5.00                0                0                 0
27                3.00                0                0                 0
28                4.15                0                0                 0
29                5.00                0                0                 0
...                ...              ...              ...               ...
1518139           3.44                0                0                 0
1518140           5.00                0                0                 0
1518141           3.42                0                0                 0
1518142           3.31                0                0                 0
1518143           4.25                0                0                 0
1518144           1.98                0                0                 0
1518145           5.00                0                0                 0
1518146           4.00                0                0                 0
1518147           4.60                0                0                 0
1518148           4.13                0                0                 0
1518149           3.60                0                0                 0
1518150           5.00                0                0                 0
1518151           4.25                1                0                 1
1518152           3.05                0                0                 0
1518153           4.00                0                0                 0
1518154           3.35                0                0                 0
1518155           3.00                0                0                 0
1518156           5.00                0                0                 0
1518157           5.00                0                0                 0
1518158           3.89                1                0                 1
1518159           3.12                0                0                 0
1518160           3.00                0                0                 0
1518161           2.33                0                0                 0
1518162           3.86                0                0                 0
1518163           5.00                0                0                 0
1518164           4.00                0                0                 0
1518165           5.00                0                0                 0
1518166           1.00                0                0                 0
1518167           3.73                0                0                 0
1518168           5.00                0                0                 0

         compliment_hot  compliment_list  compliment_more  compliment_note  \
0                     0                0                0                0
1                     0                0                0                0
2                     0                0                0                0
3                     0                0                0                0
4                     0                0                0                0
5                     0                0                0                0
6                     0                0                0                0
7                     0                0                0                0
8                     0                0                0                0
9                     0                0                0                0
10                    0                0                0                0
11                    0                0                0                0
12                    0                0                0                0
13                    0                0                0                0
14                    0                0                0                0
15                    0                0                0                0
16                    0                0                0                0
17                    0                0                0                0
18                    0                0                0                0
19                    0                0                0                0
20                    0                0                0                0
21                    0                0                0                0
22                    0                0                0                0
23                    0                0                0                0
24                    0                0                0                0
25                    0                0                0                0
26                    0                0                0                0
27                    0                0                0                0
28                    0                0                0                0
29                    0                0                0                0
...                 ...              ...              ...              ...
1518139               0                0                0                1
1518140               0                0                0                0
1518141               0                0                0                0
1518142               0                0                0                0
1518143               0                0                0                0
1518144               0                0                0                3
1518145               0                0                0                0
1518146               0                0                0                0
1518147               0                0                0                0
1518148               0                0                0                0
1518149               0                0                0                0
1518150               0                0                0                0
1518151               0                0                0                1
1518152               0                0                0                1
1518153               0                0                0                0
1518154               0                0                0                0
1518155               0                0                0                0
1518156               0                0                0                0
1518157               0                0                0                0
1518158               0                0                0                2
1518159               0                0                0                0
1518160               0                0                0                0
1518161               0                0                0                0
1518162               0                0                0                0
1518163               0                0                0                0
1518164               0                0                0                0
1518165               0                0                0                0
1518166               0                0                0                0
1518167               0                0                0                0
1518168               0                0                0                0

         compliment_photos  compliment_plain      ...        cool  elite  \
0                        0                 0      ...           0   None
1                        0                 0      ...           0   None
2                        0                 0      ...           0   None
3                        0                 0      ...           0   None
4                        0                 0      ...           0   None
5                        0                 0      ...           0   None
6                        0                 0      ...           0   None
7                        0                 0      ...           0   None
8                        0                 0      ...           0   None
9                        0                 0      ...           1   None
10                       0                 0      ...           0   None
11                       0                 0      ...           0   None
12                       0                 0      ...           0   None
13                       0                 0      ...           0   None
14                       0                 0      ...           0   None
15                       0                 0      ...           0   None
16                       0                 0      ...           0   None
17                       0                 0      ...           0   None
18                       0                 0      ...          11   None
19                       0                 0      ...           0   None
20                       0                 0      ...           0   None
21                       0                 0      ...           0   None
22                       0                 0      ...           0   None
23                       0                 0      ...           0   None
24                       0                 0      ...           0   None
25                       0                 0      ...           0   None
26                       0                 0      ...           0   None
27                       0                 0      ...           0   None
28                       0                 0      ...           0   None
29                       0                 0      ...           0   None
...                    ...               ...      ...         ...    ...
1518139                  0                 2      ...         109   2016
1518140                  0                 0      ...           0   None
1518141                  0                 0      ...           0   None
1518142                  0                 0      ...           1   None
1518143                  0                 0      ...           0   None
1518144                  0                 1      ...           2   None
1518145                  0                 0      ...           0   None
1518146                  0                 0      ...           0   None
1518147                  0                 0      ...           0   None
1518148                  0                 0      ...           0   None
1518149                  0                 0      ...           0   None
1518150                  0                 0      ...           0   None
1518151                  0                 0      ...           0   None
1518152                  0                 0      ...           0   None
1518153                  0                 0      ...           0   None
1518154                  0                 0      ...           0   None
1518155                  0                 0      ...           0   None
1518156                  0                 0      ...           0   None
1518157                  0                 0      ...           0   None
1518158                  0                 0      ...           1   None
1518159                  0                 0      ...           0   None
1518160                  0                 0      ...           0   None
1518161                  0                 0      ...           0   None
1518162                  0                 0      ...           0   None
1518163                  0                 0      ...           0   None
1518164                  0                 0      ...           0   None
1518165                  0                 0      ...           0   None
1518166                  0                 0      ...           0   None
1518167                  0                 0      ...           0   None
1518168                  0                 0      ...           0   None

         fans friends  funny          name  review_count useful  \
0           0    None      0         Susan             1      0
1           0    None      0      Daipayan             2      0
2           0    None      0          Andy             1      0
3           0    None      0      Jonathan            19      0
4           0    None      0      Shashank             3      0
5           0    None      0  Stacey X Joe             3      0
6           0    None      0       Lindsay             2      0
7           0    None      0        Joshua             1      0
8           1    None      0          Mike            11      8
9           0    None      3         Mitch             4      2
10          0    None      0        Andrea             1      0
11          0    None      0             F            10      0
12          0    None      0       Jessica             6      0
13          0    None      0          Alex             1      0
14          0    None      0          Kara             1      0
15          0    None      0        Teresa             2      1
16          0    None      0      Danielle             2      2
17          0    None      0         Shawn             4      0
18          1    None      1  Love America            16      5
19          0    None      0       Matthew             1      0
20          0    None      0           Kim             2      0
21          0    None      0          Ying             1      0
22          0    None      0          John             3      0
23          0    None      0          Kaye             2      0
24          0    None      0          Matt             5      0
25          0    None      0           Tim             1      0
26          0    None      0        Sandra             1      0
27          0    None      0         Aisha             2      0
28          0    None      0          Dana            13      0
29          0    None      0        Teresa             1      0
...       ...     ...    ...           ...           ...    ...
1518139     0    None    118         Karen            74    237
1518140     0    None      0        Lauren             1      0
1518141     0    None      0          Neda            11      1
1518142     0    None     35        Morena            27     58
1518143     0    None      0       Jerusha            16      0
1518144     0    None      0          Khan            44     18
1518145     0    None      0          Adam             2      0
1518146     0    None      0         Helen             3      0
1518147     0    None      0       Makenna            15      1
1518148     0    None      0           joe            16      0
1518149     0    None      0      Jessicca            10      0
1518150     0    None      0     Bachtuyet             1      0
1518151     0    None      0         Brent             4      1
1518152     0    None      0       Michael            18      0
1518153     0    None      0        Daniel            10      2
1518154     1    None      0           Art            16      0
1518155     0    None      0         Elena             4      0
1518156     0    None      1             P             2      1
1518157     0    None      0         Scott             2      2
1518158     0    None      1      Prescott            56      5
1518159     1    None      0         Nancy            32      0
1518160     0    None      0         Diego             3      0
1518161     0    None      0          Sean             6      3
1518162     0    None      0     Stephanie             6      0
1518163     0    None      0          Beth             1      0
1518164     0    None      0     Stephanie             1      0
1518165     0    None      0      Nicholas             4      0
1518166     1    None      0      Danielle             1      0
1518167     0    None      0          Eden            14      0
1518168     0    None      0         Margo             3      2

                        user_id  yelping_since
0        lzlZwIpuSWXEnNS91wxjHw     2015-09-28
1        XvLBr-9smbI0m_a7dXtB7w     2015-09-05
2        QPT4Ud4H5sJVr68yXhoWFw     2016-07-21
3        i5YitlHZpf0B3R0s_8NVuw     2014-08-04
4        s4FoIXE_LSGviTHBe8dmcg     2017-06-18
5        ZcsZdHLiJGVvDHVjeTYYnQ     2014-08-27
6        h3p6aeVL7vrafSOM50SsCg     2016-02-02
7        EbJMotYYkq-iq-v1u8wCYA     2013-03-20
8        nnB0AE1Cxp_0154xkhXelw     2014-07-11
9        XoEnrhtJc2pcdlQ09d8Oug     2013-04-07
10       QDQTMYp2NocktWN5fHwfIg     2017-03-25
11       Nq9WrJcCjQjHSoaUPZcPWg     2015-10-04
12       SgYDjNCecPidsRB_su5-tw     2011-01-25
13       AUWHIxgZuL2h4svVLdUZaA     2017-08-23
14       jlCxOfVf_Ff4YgGov8Tm1g     2017-11-21
15       9u9a9JakFNHZksptLKPUrw     2014-10-26
16       NfE1uHFWzzMyXkgBeEuR1A     2015-07-19
17       RiBVI6UgLjfpA4EQ1SWDzA     2014-06-15
18       iK_Mfq3BLLxprw4Trgc4Bg     2016-05-01
19       kPAyx-80ZIFKVy6uQ71I6Q     2015-05-07
20       UI_EvU0TUNeFJMNQIut--A     2015-03-01
21       bwPVGW1Mx0qmS_qNQ7xmYg     2012-02-09
22       vLekYe1hK12NJc8PyxRjIg     2012-10-09
23       bVBLhbpER9SQW9q2X-22dQ     2014-04-11
24       ibLa3RJIF8Ht0FKSXrw0TA     2013-07-02
25       wpIu6p4DYRx--gHjMbqPlw     2009-11-03
26       x-IMCiS9SBrnm8mD1WIeMg     2015-04-05
27       TpE_T9jESeq-YtqWLyyACQ     2009-05-08
28       XZFlH0CO2Txp2OVynS0Zag     2016-07-08
29       5_549BpxlmfCvkQa9mybBA     2016-03-01
...                         ...            ...
1518139  qGfqAyyPIWoFZ0JC6yClgw     2012-01-16
1518140  kP7BZegnSiurXwfYvGGpDw     2014-10-29
1518141  _upJkCGmMIxPsEkY91BkYg     2015-06-24
1518142  JDOEDdY30eMfRTjitEnMeg     2014-12-11
1518143  iLfmWoSXID1t36mJOgQXHQ     2013-09-08
1518144  60zMHHm6wpOFqCHG4OV81w     2014-06-02
1518145  a8mOFGT4ycNL20TCEFkqaA     2012-10-07
1518146  HLKhSv25-sJ3YE-OWL1xcQ     2015-08-02
1518147  69VNRfJ47FgGnGk0Pv8rdw     2014-08-27
1518148  4fpV39jHCuVoJS4SX7q3Dg     2011-08-21
1518149  kwQ3BMAx-_cHmfEFH5qTfw     2013-04-06
1518150  LHsZpDiSLX0Ru1QrR0O-vw     2018-05-20
1518151  c-cVGZ2nMZykcPIty31ACQ     2013-03-14

In [9]:
df_user.describe()

,average_stars,compliment_cool,compliment_cute,compliment_funny,compliment_hot,compliment_list,compliment_more,compliment_note,compliment_photos,compliment_plain,compliment_profile,compliment_writer,cool,fans,funny,review_count,useful
count,1.518169e+06,1.518169e+06,1.518169e+06,1.518169e+06,1.518169e+06,1.518169e+06,1.518169e+06,1.518169e+06,1.518169e+06,1.518169e+06,1.518169e+06,1.518169e+06,1.518169e+06,1.518169e+06,1.518169e+06,1.518169e+06,1.518169e+06
mean,3.716941e+00,3.257744e+00,2.030696e-01,3.257744e+00,2.351439e+00,8.959674e-02,3.496482e-01,1.550980e+00,1.161873e+00,3.239886e+00,2.257515e-01,1.225092e+00,1.912421e+01,1.453618e+00,1.399221e+01,2.243219e+01,2.866694e+01
std,1.133998e+00,8.910309e+01,1.315116e+01,8.910309e+01,7.944780e+01,1.129681e+01,1.411544e+01,5.734051e+01,9.679741e+01,9.271578e+01,1.676400e+01,3.325393e+01,6.978946e+02,1.519258e+01,5.225402e+02,7.750849e+01,7.301740e+02
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,3.070000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00
50%,3.920000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00,0.000000e+00
75%,4.670000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+01,3.000000e+00
max,5.000000e+00,3.069900e+04,1.364800e+04,3.069900e+04,3.353400e+04,1.266300e+04,1.349400e+04,5.747500e+04,8.259300e+04,4.862800e+04,1.416500e+04,1.543300e+04,2.559090e+05,8.665000e+03,2.421200e+05,1.272300e+04,2.584790e+05