In [24]:
import json
import pandas as pd
import numpy as np

In [26]:
with open('data/yelp-dataset/yelp_academic_dataset_checkin.json') as fp:
    json_checkin = fp.readlines()  #cy：我不是很确定 readlines 合不合适。我assume了每个id都是单独的一行
json_checkin[2]

'{"time":{"Thu-0":1,"Mon-1":1,"Mon-12":1,"Sat-16":1,"Sun-22":1,"Fri-23":1},"business_id":"tJRDll5yqpZwehenzE2cSg"}\n'

In [27]:
type(json_checkin)

list

In [29]:
list_ = []
for i_line in json_checkin:
    list_.append(json.loads(i_line))
list_[1]

{'time': {'Mon-13': 1,
  'Thu-13': 1,
  'Sat-16': 1,
  'Wed-17': 1,
  'Sun-19': 1,
  'Thu-20': 1,
  'Sat-21': 1},
 'business_id': 'kREVIrSBbtqBhIYkTccQUg'}

In [35]:
df_checkin = pd.DataFrame(list_)
print(df_checkin.isna().sum())
df_checkin

business_id    0
time           0
dtype: int64

,business_id,time
0,7KPBkxAOEtb3QeIL9PEErg,"{'Fri-0': 2, 'Sat-0': 1, 'Sun-0': 1, 'Wed-0': ..."
1,kREVIrSBbtqBhIYkTccQUg,"{'Mon-13': 1, 'Thu-13': 1, 'Sat-16': 1, 'Wed-1..."
2,tJRDll5yqpZwehenzE2cSg,"{'Thu-0': 1, 'Mon-1': 1, 'Mon-12': 1, 'Sat-16'..."
3,tZccfdl6JNw-j5BKnCTIQQ,"{'Sun-14': 1, 'Fri-18': 1, 'Mon-20': 1}"
4,r1p7RAMzCV_6NPF0dNoR3g,"{'Sat-3': 1, 'Sun-18': 1, 'Sat-21': 1, 'Sat-23..."
5,OVkBMWxUBXGoO4K3_CeJ7g,"{'Sat-17': 1, 'Sat-18': 1}"
6,fW1SKSunVnlaq-fxZ-gSUQ,"{'Sun-0': 1, 'Thu-0': 1, 'Sun-1': 1, 'Sat-15':..."
7,mDdqgfrvROGAumcQdZ3HIg,"{'Fri-2': 1, 'Fri-11': 1, 'Thu-11': 3, 'Mon-12..."
8,nhZ1HGWD8lMErdn3FuWuTQ,"{'Fri-0': 1, 'Sat-0': 1, 'Sun-0': 1, 'Thu-0': ..."
9,vDoXZGE7p6xAkKQ0XQPvoA,"{'Thu-15': 1, 'Sat-23': 1}"
10,8bY6M2yiWOF2ilfmGS34Fw,"{'Sat-11': 1, 'Fri-13': 1, 'Thu-14': 1}"
11,zNVot5_XHsxwfKdiFjk_aA,"{'Mon-0': 1, 'Sat-0': 1, 'Fri-1': 1, 'Sun-1': ..."
12,BH0K6SxPnY3wTRB7tA27hQ,"{'Fri-0': 1, 'Sun-0': 1, 'Thu-0': 1, 'Wed-0': ..."
13,dPxL6P_Gp74CqSPuL59Srg,"{'Tue-0': 2, 'Wed-0': 1, 'Wed-2': 1, 'Mon-10':..."
14,aZbbt_RPKV8vUY7GWiEEyw,{'Thu-18': 1}
15,ioUgJo6Euo0su-dOxUzMqA,{'Sat-16': 1}
16,Fu-egVPTQZ3lNYM0PhpQiQ,"{'Thu-14': 1, 'Sat-15': 1, 'Mon-17': 1, 'Wed-1..."
17,HRIUU2Z4EsZBo59P0I2ZYA,"{'Fri-0': 1, 'Tue-0': 1, 'Wed-0': 2, 'Mon-1': ..."
18,Y6L37i6rkqDzMesTN5UI2Q,"{'Sun-0': 1, 'Thu-0': 1, 'Tue-0': 2, 'Wed-0': ..."
19,WllBAxQd6w3EZHYNOKRoMw,"{'Thu-15': 1, 'Mon-20': 1}"
20,SNtC3y4G5UzNnQ_zYxW7dQ,"{'Tue-0': 1, 'Tue-1': 1, 'Wed-1': 2, 'Thu-2': ..."
21,FQM4pVt1jeZcBGLIsXhXNA,"{'Sat-0': 1, 'Sun-0': 1, 'Thu-0': 2, 'Tue-0': ..."
22,z3yMZ628sZP5yfWAnaA04Q,"{'Wed-0': 1, 'Mon-11': 1, 'Thu-13': 1, 'Sat-19..."
23,0WsCtzG8xazAmFA5HhQE0A,"{'Sun-0': 2, 'Thu-0': 1, 'Sat-1': 1, 'Sun-1': ..."
24,yEWrdUczj1_9KTUJEVfIIg,"{'Sat-0': 1, 'Tue-0': 1, 'Fri-2': 1, 'Sun-3': ..."
25,RGeEUbXNFPqozawExgvy_g,"{'Sat-14': 1, 'Fri-17': 1, 'Wed-17': 1, 'Mon-1..."
26,JN6287XepTV2wOiwnq5joA,"{'Wed-0': 1, 'Tue-21': 1, 'Sat-23': 1}"
27,vl02XdFVoXC-s_Y4WVvL-g,"{'Mon-12': 1, 'Tue-13': 1, 'Sat-21': 1, 'Fri-2..."
28,zek4x_a6Io6mU67bc4ahXA,"{'Fri-0': 1, 'Mon-0': 2, 'Sun-0': 1, 'Thu-0': ..."
29,d2yEVlD-cGHj7p_cb7FqqQ,"{'Fri-0': 1, 'Sun-0': 2, 'Wed-0': 1, 'Sat-14':..."
...,...,...
157045,Vx5G6wgRg9EI64Jbq31Ckw,"{'Fri-0': 9, 'Fri-1': 9, 'Thu-23': 1}"
157046,ch_XGu7FpwGKp9m8Xy4vPA,"{'Sun-0': 1, 'Thu-0': 1, 'Fri-1': 1, 'Sat-1': ..."
157047,5ayNBWXT7BtrW2285_nb9Q,"{'Sun-22': 1, 'Tue-22': 1}"
157048,2KfZjPnMm8NfILHccj-lBQ,{'Sat-0': 1}
157049,meMEbONCUMmY6MiamrcufA,"{'Thu-0': 1, 'Sun-1': 1, 'Wed-23': 1}"
157050,9kFKG-MyIEh5Fteb3-6Yxg,"{'Fri-2': 1, 'Sat-2': 1, 'Tue-2': 1, 'Sun-4': ..."
157051,QQ4763IteaX73s6-1d68dw,"{'Tue-15': 1, 'Mon-16': 1}"
157052,5R7dT5TPfNsOMenkbHiYbQ,"{'Tue-1': 1, 'Wed-2': 1, 'Sun-3': 1, 'Wed-3': ..."
157053,L79b_FccWEKr-lON9tx5-g,"{'Sun-1': 1, 'Sun-2': 1, 'Mon-5': 1, 'Sat-21': 1}"
157054,knLeOVOws25-hFvTWELhaQ,{'Mon-20': 2}
157055,oQhwzyxI_OXQAA049yRbFg,"{'Mon-8': 1, 'Tue-15': 1, 'Sun-19': 8, 'Sun-20..."
157056,wVXaRR7ML_52wR8BiBdyaQ,"{'Fri-21': 2, 'Fri-22': 7, 'Fri-23': 1}"
157057,2ZOjUr9wtD1MypDYZRCiHQ,"{'Sat-0': 1, 'Sat-19': 1, 'Sat-23': 1, 'Tue-23..."
157058,RP79t7P6PZYoILkMkhkt6A,{'Sun-21': 1}
157059,Azy2vmC47uHSkZE2fdvBjA,"{'Sat-1': 1, 'Sat-18': 1, 'Wed-21': 1, 'Fri-22..."
157060,nYvBZYg9rfqWFTYuxSVMdw,"{'Sun-16': 1, 'Sun-19': 1, 'Thu-21': 1}"
157061,0O5vnpFgp10CGPgX5dOPzA,"{'Sat-1': 1, 'Mon-19': 1, 'Sun-20': 1, 'Tue-20..."
157062,3-1SCOk_hEgZp5kbLr-Y-w,"{'Tue-16': 1, 'Tue-17': 4}"
157063,nZVXfMWyADZEvuGb4R4RVg,"{'Fri-0': 9, 'Fri-2': 1, 'Fri-3': 1, 'Fri-12':..."
157064,AN9r4LysbyTaCZgTJzkLfQ,{'Mon-20': 1}
157065,Gho38SoO_9dq6hhT4Ll-5g,{'Tue-1': 1}
157066,Q6cgDdRy8BCmw745WZJCxA,"{'Fri-7': 1, 'Sun-18': 2, 'Mon-19': 1, 'Sat-19..."
157067,iJP3JaOCiturjKRqp5mllQ,"{'Wed-4': 1, 'Tue-20': 13, 'Tue-21': 11, 'Tue-..."
157068,i-asrwC0dAM9HSHuRMuIRg,"{'Sun-16': 11, 'Sun-17': 10, 'Sun-18': 2}"
157069,9f5RGQpIjiVPY4h5ppj1yw,"{'Fri-3': 1, 'Mon-15': 1, 'Mon-16': 2}"
157070,G6zYdHNPqSbw_Nom8ZxtVA,"{'Sat-0': 1, 'Fri-19': 1}"
157071,vMF4euV_C_2e_2H3F-OCUg,"{'Thu-21': 1, 'Thu-22': 12, 'Thu-23': 1}"
157072,C_-8AEMAJG6MvE3b6ou-ow,"{'Wed-22': 1, 'Fri-23': 1}"
157073,rCMWUkhQ3phhBUlXevrkfg,"{'Mon-17': 1, 'Sat-19': 1, 'Sun-20': 1}"
157074,bWhs2V3B65zu9of0CjQSzg,"{'Sat-6': 1, 'Sun-22': 1}"

In [31]:
df_checkin.time.iloc[0]

{'Fri-0': 2,
 'Sat-0': 1,
 'Sun-0': 1,
 'Wed-0': 2,
 'Fri-1': 1,
 'Sat-1': 3,
 'Thu-1': 1,
 'Wed-1': 1,
 'Sat-2': 1,
 'Sun-2': 2,
 'Thu-2': 1,
 'Wed-2': 1,
 'Fri-3': 1,
 'Sun-3': 3,
 'Mon-4': 1,
 'Thu-4': 1,
 'Tue-4': 2,
 'Wed-4': 2,
 'Sun-6': 1,
 'Wed-6': 1,
 'Thu-7': 1,
 'Fri-10': 3,
 'Mon-10': 1,
 'Sat-10': 3,
 'Sun-10': 3,
 'Tue-10': 2,
 'Mon-11': 1,
 'Thu-11': 1,
 'Wed-11': 2,
 'Mon-12': 1,
 'Sat-12': 1,
 'Tue-12': 1,
 'Sat-13': 3,
 'Thu-13': 1,
 'Tue-13': 2,
 'Wed-13': 3,
 'Fri-14': 2,
 'Mon-14': 1,
 'Sat-14': 1,
 'Sun-14': 1,
 'Tue-14': 1,
 'Wed-14': 2,
 'Fri-15': 1,
 'Mon-15': 1,
 'Sat-15': 1,
 'Thu-15': 2,
 'Tue-15': 1,
 'Fri-16': 1,
 'Sat-16': 2,
 'Sun-16': 1,
 'Thu-16': 1,
 'Tue-16': 1,
 'Fri-17': 1,
 'Mon-17': 3,
 'Sat-17': 4,
 'Sun-17': 1,
 'Tue-17': 1,
 'Wed-17': 1,
 'Fri-18': 1,
 'Mon-18': 1,
 'Sat-18': 4,
 'Sun-18': 1,
 'Thu-18': 1,
 'Tue-18': 2,
 'Wed-18': 1,
 'Fri-19': 3,
 'Mon-19': 1,
 'Sun-19': 2,
 'Thu-19': 1,
 'Wed-19': 1,
 'Mon-20': 1,
 'Sun-20': 5,
 'Thu-20': 4,
 'Tue-20': 2,
 'Wed-20': 3,
 'Fri-21': 4,
 'Mon-21': 1,
 'Sat-21': 1,
 'Sun-21': 1,
 'Thu-21': 4,
 'Tue-21': 1,
 'Wed-21': 1,
 'Fri-22': 3,
 'Thu-22': 1,
 'Fri-23': 1,
 'Mon-23': 2,
 'Sat-23': 3,
 'Sun-23': 1,
 'Thu-23': 2,
 'Tue-23': 2}